### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by wheelebigger** [fman-users/Core#1]
Since we're able to change font-sizes with Theme.css - is there a way to change the icon-size?
I'm referring to the file-, and folder-icons.

I tried googling it but couldn't find anything about the icons.

**Comment by mherrmann** [comment]
I'm afraid that's not possible at the moment no, sorry.

**Comment by mherrmann** [comment]
(Also I'm closing this issue because it belongs in https://github.com/fman-users/fman.)

**Comment by wheelebigger** [comment]
> (Also I'm closing this issue because it belongs in https://github.com/fman-users/fman.)

Oh sorry, i'm not too savvy at doing these things on github.
Thx for the reply - was more of a hopeful suggestion than an "issue" per se. 
Thx for the great product!

**Comment by mherrmann** [comment]
No problem. I'm happy to hear you like fman :)
